node:
  build: ./node
  environment:
    - 'PORT=4000'
  ports:
    - "4000:4000"
  links:
    - rabbitmq
rabbitmq:
  image: rabbitmq:3.6-management
  ports:
    - "8080:8080"
    - "5672:5672"
    - "15672:15672"
rethinkdb:
  image: rethinkdb:2.3.2
  ports:
    - "8081:8080"
    - "28015:28015"
