node:
  build: ./node
  environment:
    - 'PORT=4000'
  ports:
    - "4000:4000"
  links:
    - rabbitmq
net:
  build: ./net
  environment:
    - 'PORT=5000'
  ports:
    - "5000:5000"
  links:
    - rabbitmq
rabbitmq:
  image: rabbitmq:3.6.1
  ports:
    - "8080:8080"
    - "15672:15672"
